--sparks from damaged units that repair
return {
  ["repairsparks"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 1,
      flashsize          = 20,
      ttl                = 3,
      color = {
        [1]  = 0,
        [2]  = 1,
        [3]  = 1,
      },
    },
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 5,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.05,
        color              = [[0.5,1,1]],
        dir                = [[-1 r2,-1 r2,-1 r2]],
        length             = 5,
        width              = 10,
      },
    },
    sparks = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 1 1 0.01   1 0.7 0.2 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.4, 0]],
        numparticles       = 20,
        particlelife       = 15,
        particlelifespread = 10,
        particlesize       = 1,
        particlesizespread = 2.5,
        particlespeed      = 6,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[trailball]],
      },
    },
  },
 }
