--temp ceg for testing
--based on "tremor" ceg from zero k

return {
  ["tptestceg"] = {
    air                = true,
    count              = 1,
    ground             = true,
    water              = false,
    debris1 = { --stuff that does outwards
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 5,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.22 0.18 0.15 1   0.22 0.18 0.15 1	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 5,
        particlelife       = [[30 i-0.5]],
        particlelifespread = 0,
        particlesize       = [[30 r10]],
        particlesizespread = 0,
        particlespeed      = 4,
        particlespeedspread = 1,
        pos                = [[0, -2, 0]],
        sizegrowth         = [[-0.1 i0.015]],
        sizemod            = 1.0,
        texture            = [[splatter]],
      },
    },
    dirt1 = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.5 0.3 0.3  0.45 0.37 0.3 1  0.45 0.37 0.3 1	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 30,
        particlelifespread = 3,
        particlesize       = 2.3,
        particlesizespread = 1,
        particlespeed      = 0,
        particlespeedspread = 19,
        pos                = [[0, -2, 0]],
        sizegrowth         = 3,
        sizemod            = 1.0,
        texture            = [[splatter]],
      },
    },
    dirt2 = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.5 0.2 0.8	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 20,
        particlelifespread = 3,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = 0,
        particlespeedspread = 19,
        pos                = [[0, -2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[greyblob]],
      },
    },
	
	flamespikes = {
      air                = true,
      class              = [[explspike]],
      count              = 15,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.2,
        color              = [[1 ,0.9 ,0.9]],
        --dir                = [[-15 r50,-15 r50,-15 r50]],
		dir                = [[-10 r10,-5 r5,-10 r10]],
        length             = 30,
        width              = 5,
      },
    },
	
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1,
      flashalpha         = 0.99,
      flashsize          = 100,
      ttl                = 10,
      color = {
        [1]  = 1,
        [2]  = 0.9,
        [3]  = 0.5,
      },
    },
  },

}

