gp = piece "gp"
cod = piece "cod"
base = piece "base"
head = piece "head"
left = piece "left"
l_arm = piece "l_arm"
l_forearm = piece "l_forearm"
right = piece "right"
r_arm = piece "r_arm"
r_forearm = piece "r_forearm"
gun = piece "gun"
fire = piece "fire"
right_l = piece "right_l"
shin_r = piece "shin_r"
foot_r = piece "foot_r"
left_l = piece "left_l"
shin_l = piece "shin_l"
foot_l = piece "foot_l"


function script.Create()
	
	--StartThread (animatejump)
	--StartThread (animatesalto)
	StartThread (animatesalut)
end

--does not work
function animatesalto()
	while (true) do
	salto1(100,math.rad(180))
	Sleep(800)
	salto2(100,math.rad(180))
	Sleep(800)
	salto3(100,math.rad(180))
	Sleep(800)
	salto4(100,math.rad(180))
	Sleep (800)
	salto5(100,math.rad(180))
	Sleep (800)
	salto6(100,math.rad(180))
	Sleep (800)
	end
end

function animatejump ()
	while (true) do
	--Spring.Echo ("derp!")
	slightknee()
	Sleep (1100)
	xjump()
	Sleep (600)
	end
end

function animatesalut ()
	while (true) do	
	lookright(100,math.rad(180))
	Sleep (2000)
	lookleft(100,math.rad(180))	
	Sleep (700)
	lookright(100,math.rad(90))
	Sleep (1500)
	bothhandgrip(100,math.rad(180))
	Sleep (1500)
	salut (100,math.rad(180))
	Sleep (800)
	end
end


function xjump ()
local mspeed=50
local tspeed=math.rad(180)
Move (gp, x_axis, 0, mspeed)
Move (gp, y_axis, 0, mspeed)
Move (gp, z_axis, 0, mspeed)
Turn (gp, x_axis, 0, tspeed)
Turn (gp, y_axis, 0, tspeed)
Turn (gp, z_axis, 0, tspeed)
Move (cod, x_axis, 1, mspeed)
Move (cod, y_axis, 16, mspeed)
Move (cod, z_axis, 0, mspeed)
Turn (cod, x_axis, 0, tspeed)
Turn (cod, y_axis, 0, tspeed)
Turn (cod, z_axis, 0, tspeed)
Move (base, x_axis, 0, mspeed)
Move (base, y_axis, 0, mspeed)
Move (base, z_axis, 0, mspeed)
Turn (base, x_axis, -0.34906584024429, tspeed)
Turn (base, y_axis, 0, tspeed)
Turn (base, z_axis, 0, tspeed)
Move (head, x_axis, 0, mspeed)
Move (head, y_axis, 0, mspeed)
Move (head, z_axis, 0, mspeed)
Turn (head, x_axis, -0.34906581044197, tspeed)
Turn (head, y_axis, 0.34906584024429, tspeed)
Turn (head, z_axis, 2.9802322387695e-008, tspeed)
Move (left, x_axis, 0, mspeed)
Move (left, y_axis, 0, mspeed)
Move (left, z_axis, 0, mspeed)
Turn (left, x_axis, -2.9670593738556, tspeed)
Turn (left, y_axis, 0, tspeed)
Turn (left, z_axis, 0, tspeed)
Move (l_arm, x_axis, 0, mspeed)
Move (l_arm, y_axis, 0, mspeed)
Move (l_arm, z_axis, 0, mspeed)
Turn (l_arm, x_axis, 0, tspeed)
Turn (l_arm, y_axis, 0, tspeed)
Turn (l_arm, z_axis, 0.34906584024429, tspeed)
Move (l_forearm, x_axis, 0, mspeed)
Move (l_forearm, y_axis, 0, mspeed)
Move (l_forearm, z_axis, 0, mspeed)
Turn (l_forearm, x_axis, 0, tspeed)
Turn (l_forearm, y_axis, 0, tspeed)
Turn (l_forearm, z_axis, 0, tspeed)
Move (right, x_axis, 0, mspeed)
Move (right, y_axis, 0, mspeed)
Move (right, z_axis, 0, mspeed)
Turn (right, x_axis, 0, tspeed)
Turn (right, y_axis, 0, tspeed)
Turn (right, z_axis, 0, tspeed)
Move (r_arm, x_axis, 0, mspeed)
Move (r_arm, y_axis, 0, mspeed)
Move (r_arm, z_axis, 0, mspeed)
Turn (r_arm, x_axis, -2.6179935932159, tspeed)
Turn (r_arm, y_axis, 0, tspeed)
Turn (r_arm, z_axis, 0, tspeed)
Move (r_forearm, x_axis, 0, mspeed)
Move (r_forearm, y_axis, 0, mspeed)
Move (r_forearm, z_axis, 0, mspeed)
Turn (r_forearm, x_axis, 0, tspeed)
Turn (r_forearm, y_axis, 0, tspeed)
Turn (r_forearm, z_axis, -0.17453292012215, tspeed)
Move (gun, x_axis, 0, mspeed)
Move (gun, y_axis, 0, mspeed)
Move (gun, z_axis, 0, mspeed)
Turn (gun, x_axis, 0, tspeed)
Turn (gun, y_axis, 0, tspeed)
Turn (gun, z_axis, 0, tspeed)
Move (fire, x_axis, 0, mspeed)
Move (fire, y_axis, 0, mspeed)
Move (fire, z_axis, 0, mspeed)
Turn (fire, x_axis, 0, tspeed)
Turn (fire, y_axis, 0, tspeed)
Turn (fire, z_axis, 0, tspeed)
Move (right_l, x_axis, 0, mspeed)
Move (right_l, y_axis, 0, mspeed)
Move (right_l, z_axis, 0, mspeed)
Turn (right_l, x_axis, 0, tspeed)
Turn (right_l, y_axis, -0.34906584024429, tspeed)
Turn (right_l, z_axis, -0.34906584024429, tspeed)
Move (shin_r, x_axis, 0, mspeed)
Move (shin_r, y_axis, 0, mspeed)
Move (shin_r, z_axis, 0, mspeed)
Turn (shin_r, x_axis, 0.17453292012215, tspeed)
Turn (shin_r, y_axis, 0, tspeed)
Turn (shin_r, z_axis, 0, tspeed)
Move (foot_r, x_axis, 0, mspeed)
Move (foot_r, y_axis, 0, mspeed)
Move (foot_r, z_axis, 0, mspeed)
Turn (foot_r, x_axis, 0.52359879016876, tspeed)
Turn (foot_r, y_axis, 0, tspeed)
Turn (foot_r, z_axis, 0, tspeed)
Move (left_l, x_axis, 0, mspeed)
Move (left_l, y_axis, 0, mspeed)
Move (left_l, z_axis, 0, mspeed)
Turn (left_l, x_axis, 0, tspeed)
Turn (left_l, y_axis, 0, tspeed)
Turn (left_l, z_axis, 0.34906584024429, tspeed)
Move (shin_l, x_axis, 0, mspeed)
Move (shin_l, y_axis, 0, mspeed)
Move (shin_l, z_axis, 0, mspeed)
Turn (shin_l, x_axis, 0.34906584024429, tspeed)
Turn (shin_l, y_axis, 0, tspeed)
Turn (shin_l, z_axis, 0.17453292012215, tspeed)
Move (foot_l, x_axis, 0, mspeed)
Move (foot_l, y_axis, 0, mspeed)
Move (foot_l, z_axis, 0, mspeed)
Turn (foot_l, x_axis, 0.17453292012215, tspeed)
Turn (foot_l, y_axis, 0, tspeed)
Turn (foot_l, z_axis, 0, tspeed)

end

function derp()
mspeed=10
tspeed=math.rad(180)
 Move (gp, x_axis, 0, mspeed)
 Move (gp, y_axis, 0, mspeed)
 Move (gp, z_axis, 0, mspeed)
 Turn (gp, x_axis, 0, tspeed)
 Turn (gp, y_axis, 0, tspeed)
 Turn (gp, z_axis, 0, tspeed)
 Move (cod, x_axis, 0, mspeed)
 Move (cod, y_axis, 0, mspeed)
 Move (cod, z_axis, 0, mspeed)
 Turn (cod, x_axis, 0, tspeed)
 Turn (cod, y_axis, 0, tspeed)
 Turn (cod, z_axis, 0, tspeed)
 Move (base, x_axis, 0, mspeed)
 Move (base, y_axis, 0, mspeed)
 Move (base, z_axis, 0, mspeed)
 Turn (base, x_axis, 0, tspeed)
 Turn (base, y_axis, 0, tspeed)
 Turn (base, z_axis, 0.34906584024429, tspeed)
 Move (head, x_axis, 0, mspeed)
 Move (head, y_axis, 0, mspeed)
 Move (head, z_axis, 0, mspeed)
 Turn (head, x_axis, 0, tspeed)
 Turn (head, y_axis, 0.17453292012215, tspeed)
 Turn (head, z_axis, 0, tspeed)
 Move (left, x_axis, 0, mspeed)
 Move (left, y_axis, 0, mspeed)
 Move (left, z_axis, 0, mspeed)
 Turn (left, x_axis, -1.7453290224075, tspeed)
 Turn (left, y_axis, 0, tspeed)
 Turn (left, z_axis, 0.17453292012215, tspeed)
 Move (l_arm, x_axis, 0, mspeed)
 Move (l_arm, y_axis, 0, mspeed)
 Move (l_arm, z_axis, 0, mspeed)
 Turn (l_arm, x_axis, 0, tspeed)
 Turn (l_arm, y_axis, 0, tspeed)
 Turn (l_arm, z_axis, 0, tspeed)
 Move (l_forearm, x_axis, 0, mspeed)
 Move (l_forearm, y_axis, 0, mspeed)
 Move (l_forearm, z_axis, 0, mspeed)
 Turn (l_forearm, x_axis, -1.3962632417679, tspeed)
 Turn (l_forearm, y_axis, 0, tspeed)
 Turn (l_forearm, z_axis, 0, tspeed)
 Move (right, x_axis, 0, mspeed)
 Move (right, y_axis, 0, mspeed)
 Move (right, z_axis, 0, mspeed)
 Turn (right, x_axis, 0, tspeed)
 Turn (right, y_axis, 0, tspeed)
 Turn (right, z_axis, 0, tspeed)
 Move (r_arm, x_axis, 0, mspeed)
 Move (r_arm, y_axis, 0, mspeed)
 Move (r_arm, z_axis, 0, mspeed)
 Turn (r_arm, x_axis, -1.7453290224075, tspeed)
 Turn (r_arm, y_axis, 0, tspeed)
 Turn (r_arm, z_axis, 0, tspeed)
 Move (r_forearm, x_axis, 0, mspeed)
 Move (r_forearm, y_axis, 0, mspeed)
 Move (r_forearm, z_axis, 0, mspeed)
 Turn (r_forearm, x_axis, -0.17453294992447, tspeed)
 Turn (r_forearm, y_axis, -0.17453289031982, tspeed)
 Turn (r_forearm, z_axis, -0.34906584024429, tspeed)
 Move (gun, x_axis, 0, mspeed)
 Move (gun, y_axis, 0, mspeed)
 Move (gun, z_axis, 0, mspeed)
 Turn (gun, x_axis, -0.17453292012215, tspeed)
 Turn (gun, y_axis, 0, tspeed)
 Turn (gun, z_axis, 0, tspeed)
 Move (fire, x_axis, 0, mspeed)
 Move (fire, y_axis, 0, mspeed)
 Move (fire, z_axis, 0, mspeed)
 Turn (fire, x_axis, 0, tspeed)
 Turn (fire, y_axis, 0, tspeed)
 Turn (fire, z_axis, 0, tspeed)
 Move (right_l, x_axis, 0, mspeed)
 Move (right_l, y_axis, 0, mspeed)
 Move (right_l, z_axis, 0, mspeed)
 Turn (right_l, x_axis, 0, tspeed)
 Turn (right_l, y_axis, 0, tspeed)
 Turn (right_l, z_axis, 0, tspeed)
 Move (shin_r, x_axis, 0, mspeed)
 Move (shin_r, y_axis, 0, mspeed)
 Move (shin_r, z_axis, 0, mspeed)
 Turn (shin_r, x_axis, -0.87266457080841, tspeed)
 Turn (shin_r, y_axis, 0, tspeed)
 Turn (shin_r, z_axis, -0.17453292012215, tspeed)
 Move (foot_r, x_axis, 0, mspeed)
 Move (foot_r, y_axis, 0, mspeed)
 Move (foot_r, z_axis, 0, mspeed)
 Turn (foot_r, x_axis, 0.52359879016876, tspeed)
 Turn (foot_r, y_axis, 0, tspeed)
 Turn (foot_r, z_axis, -0.17453292012215, tspeed)
 Move (left_l, x_axis, 0, mspeed)
 Move (left_l, y_axis, 0, mspeed)
 Move (left_l, z_axis, 0, mspeed)
 Turn (left_l, x_axis, 0, tspeed)
 Turn (left_l, y_axis, 0, tspeed)
 Turn (left_l, z_axis, 0, tspeed)
 Move (shin_l, x_axis, 0, mspeed)
 Move (shin_l, y_axis, 0, mspeed)
 Move (shin_l, z_axis, 0, mspeed)
 Turn (shin_l, x_axis, -0.69813168048859, tspeed)
 Turn (shin_l, y_axis, 0.87266457080841, tspeed)
 Turn (shin_l, z_axis, -0.17453294992447, tspeed)
 Move (foot_l, x_axis, 0, mspeed)
 Move (foot_l, y_axis, 0, mspeed)
 Move (foot_l, z_axis, 0, mspeed)
 Turn (foot_l, x_axis, 0, tspeed)
 Turn (foot_l, y_axis, 0, tspeed)
 Turn (foot_l, z_axis, 0, tspeed)
 end

function standnull()
	Move (gp, x_axis, 0)
	Move (gp, y_axis, 0)
	Move (gp, z_axis, 0)
	Turn (gp, x_axis, 0)
	Turn (gp, y_axis, 0)
	Turn (gp, z_axis, 0)
	Move (cod, x_axis, 0)
	Move (cod, y_axis, 0)
	Move (cod, z_axis, 0)
	Turn (cod, x_axis, 0)
	Turn (cod, y_axis, 0)
	Turn (cod, z_axis, 0)
	Move (base, x_axis, 0)
	Move (base, y_axis, 0)
	Move (base, z_axis, 0)
	Turn (base, x_axis, 0)
	Turn (base, y_axis, 0)
	Turn (base, z_axis, 0)
	Move (head, x_axis, 0)
	Move (head, y_axis, 0)
	Move (head, z_axis, 0)
	Turn (head, x_axis, 0)
	Turn (head, y_axis, 0)
	Turn (head, z_axis, 0)
	Move (left, x_axis, 0)
	Move (left, y_axis, 0)
	Move (left, z_axis, 0)
	Turn (left, x_axis, 0)
	Turn (left, y_axis, 0)
	Turn (left, z_axis, 0)
	Move (l_arm, x_axis, 0)
	Move (l_arm, y_axis, 0)
	Move (l_arm, z_axis, 0)
	Turn (l_arm, x_axis, 0)
	Turn (l_arm, y_axis, 0)
	Turn (l_arm, z_axis, 0)
	Move (l_forearm, x_axis, 0)
	Move (l_forearm, y_axis, 0)
	Move (l_forearm, z_axis, 0)
	Turn (l_forearm, x_axis, 0)
	Turn (l_forearm, y_axis, 0)
	Turn (l_forearm, z_axis, 0)
	Move (right, x_axis, 0)
	Move (right, y_axis, 0)
	Move (right, z_axis, 0)
	Turn (right, x_axis, 0)
	Turn (right, y_axis, 0)
	Turn (right, z_axis, 0)
	Move (r_arm, x_axis, 0)
	Move (r_arm, y_axis, 0)
	Move (r_arm, z_axis, 0)
	Turn (r_arm, x_axis, 0)
	Turn (r_arm, y_axis, 0)
	Turn (r_arm, z_axis, 0)
	Move (r_forearm, x_axis, 0)
	Move (r_forearm, y_axis, 0)
	Move (r_forearm, z_axis, 0)
	Turn (r_forearm, x_axis, 0)
	Turn (r_forearm, y_axis, 0)
	Turn (r_forearm, z_axis, 0)
	Move (gun, x_axis, 0)
	Move (gun, y_axis, 0)
	Move (gun, z_axis, 0)
	Turn (gun, x_axis, 0)
	Turn (gun, y_axis, 0)
	Turn (gun, z_axis, 0)
	Move (fire, x_axis, 0)
	Move (fire, y_axis, 0)
	Move (fire, z_axis, 0)
	Turn (fire, x_axis, 0)
	Turn (fire, y_axis, 0)
	Turn (fire, z_axis, 0)
	Move (right_l, x_axis, 0)
	Move (right_l, y_axis, 0)
	Move (right_l, z_axis, 0)
	Turn (right_l, x_axis, 0)
	Turn (right_l, y_axis, 0)
	Turn (right_l, z_axis, 0)
	Move (shin_r, x_axis, 0)
	Move (shin_r, y_axis, 0)
	Move (shin_r, z_axis, 0)
	Turn (shin_r, x_axis, 0)
	Turn (shin_r, y_axis, 0)
	Turn (shin_r, z_axis, 0)
	Move (foot_r, x_axis, 0)
	Move (foot_r, y_axis, 0)
	Move (foot_r, z_axis, 0)
	Turn (foot_r, x_axis, 0)
	Turn (foot_r, y_axis, 0)
	Turn (foot_r, z_axis, 0)
	Move (left_l, x_axis, 0)
	Move (left_l, y_axis, 0)
	Move (left_l, z_axis, 0)
	Turn (left_l, x_axis, 0)
	Turn (left_l, y_axis, 0)
	Turn (left_l, z_axis, 0)
	Move (shin_l, x_axis, 0)
	Move (shin_l, y_axis, 0)
	Move (shin_l, z_axis, 0)
	Turn (shin_l, x_axis, 0)
	Turn (shin_l, y_axis, 0)
	Turn (shin_l, z_axis, 0)
	Move (foot_l, x_axis, 0)
	Move (foot_l, y_axis, 0)
	Move (foot_l, z_axis, 0)
	Turn (foot_l, x_axis, 0)
	Turn (foot_l, y_axis, 0)
	Turn (foot_l, z_axis, 0)
end

function knee ()
mspeed=50
tspeed=math.rad(180)
 
 Move (gp, x_axis, 0, mspeed)
 Move (gp, y_axis, 0, mspeed)
 Move (gp, z_axis, 0, mspeed)
 Turn (gp, x_axis, 0, tspeed)
 Turn (gp, y_axis, 0, tspeed)
 Turn (gp, z_axis, 0, tspeed)
 Move (cod, x_axis, 0, mspeed)
 Move (cod, y_axis, -8, mspeed)
 Move (cod, z_axis, 0, mspeed)
 Turn (cod, x_axis, 0, tspeed)
 Turn (cod, y_axis, 0, tspeed)
 Turn (cod, z_axis, 0, tspeed)
 Move (base, x_axis, 0, mspeed)
 Move (base, y_axis, 0, mspeed)
 Move (base, z_axis, 0, mspeed)
 Turn (base, x_axis, 0, tspeed)
 Turn (base, y_axis, 0.17453289031982, tspeed)
 Turn (base, z_axis, 0, tspeed)
 Move (head, x_axis, 0, mspeed)
 Move (head, y_axis, 0, mspeed)
 Move (head, z_axis, 0, mspeed)
 Turn (head, x_axis, 0, tspeed)
 Turn (head, y_axis, 0.34906584024429, tspeed)
 Turn (head, z_axis, 0, tspeed)
 Move (left, x_axis, 0, mspeed)
 Move (left, y_axis, 0, mspeed)
 Move (left, z_axis, 0, mspeed)
 Turn (left, x_axis, 0.34906584024429, tspeed)
 Turn (left, y_axis, 0, tspeed)
 Turn (left, z_axis, 0, tspeed)
 Move (l_arm, x_axis, 0, mspeed)
 Move (l_arm, y_axis, 0, mspeed)
 Move (l_arm, z_axis, 0, mspeed)
 Turn (l_arm, x_axis, 0, tspeed)
 Turn (l_arm, y_axis, 0, tspeed)
 Turn (l_arm, z_axis, 0, tspeed)
 Move (l_forearm, x_axis, 0, mspeed)
 Move (l_forearm, y_axis, 0, mspeed)
 Move (l_forearm, z_axis, 0, mspeed)
 Turn (l_forearm, x_axis, -0.17453292012215, tspeed)
 Turn (l_forearm, y_axis, 0, tspeed)
 Turn (l_forearm, z_axis, 0, tspeed)
 Move (right, x_axis, 0, mspeed)
 Move (right, y_axis, 0, mspeed)
 Move (right, z_axis, 0, mspeed)
 Turn (right, x_axis, 0, tspeed)
 Turn (right, y_axis, 0, tspeed)
 Turn (right, z_axis, 0, tspeed)
 Move (r_arm, x_axis, 0, mspeed)
 Move (r_arm, y_axis, 0, mspeed)
 Move (r_arm, z_axis, 0, mspeed)
 Turn (r_arm, x_axis, -1.5707961320877, tspeed)
 Turn (r_arm, y_axis, 0.17453292012215, tspeed)
 Turn (r_arm, z_axis, 0, tspeed)
 Move (r_forearm, x_axis, 0, mspeed)
 Move (r_forearm, y_axis, 0, mspeed)
 Move (r_forearm, z_axis, 0, mspeed)
 Turn (r_forearm, x_axis, 0, tspeed)
 Turn (r_forearm, y_axis, 0, tspeed)
 Turn (r_forearm, z_axis, 0.17453292012215, tspeed)
 Move (gun, x_axis, 0, mspeed)
 Move (gun, y_axis, 0, mspeed)
 Move (gun, z_axis, 0, mspeed)
 Turn (gun, x_axis, 0, tspeed)
 Turn (gun, y_axis, 0, tspeed)
 Turn (gun, z_axis, 0, tspeed)
 Move (fire, x_axis, 0, mspeed)
 Move (fire, y_axis, 0, mspeed)
 Move (fire, z_axis, 0, mspeed)
 Turn (fire, x_axis, 0, tspeed)
 Turn (fire, y_axis, 0, tspeed)
 Turn (fire, z_axis, 0, tspeed)
 Move (right_l, x_axis, 0, mspeed)
 Move (right_l, y_axis, 0, mspeed)
 Move (right_l, z_axis, 1, mspeed)
 Turn (right_l, x_axis, -1.0471974611282, tspeed)
 Turn (right_l, y_axis, 0, tspeed)
 Turn (right_l, z_axis, 0, tspeed)
 Move (shin_r, x_axis, 0, mspeed)
 Move (shin_r, y_axis, 0, mspeed)
 Move (shin_r, z_axis, 0, mspeed)
 Turn (shin_r, x_axis, 1.0471974611282, tspeed)
 Turn (shin_r, y_axis, 0, tspeed)
 Turn (shin_r, z_axis, 0, tspeed)
 Move (foot_r, x_axis, 0, mspeed)
 Move (foot_r, y_axis, 0, mspeed)
 Move (foot_r, z_axis, 0, mspeed)
 Turn (foot_r, x_axis, 0, tspeed)
 Turn (foot_r, y_axis, -0.17453292012215, tspeed)
 Turn (foot_r, z_axis, 0, tspeed)
 Move (left_l, x_axis, 0, mspeed)
 Move (left_l, y_axis, 0, mspeed)
 Move (left_l, z_axis, 0, mspeed)
 Turn (left_l, x_axis, 0.87266457080841, tspeed)
 Turn (left_l, y_axis, 0, tspeed)
 Turn (left_l, z_axis, 0, tspeed)
 Move (shin_l, x_axis, 0, mspeed)
 Move (shin_l, y_axis, 0, mspeed)
 Move (shin_l, z_axis, 0, mspeed)
 Turn (shin_l, x_axis, -0.34906587004662, tspeed)
 Turn (shin_l, y_axis, 0, tspeed)
 Turn (shin_l, z_axis, 0, tspeed)
 Move (foot_l, x_axis, 0, mspeed)
 Move (foot_l, y_axis, 0, mspeed)
 Move (foot_l, z_axis, 0, mspeed)
 Turn (foot_l, x_axis, -0.52359879016876, tspeed)
 Turn (foot_l, y_axis, 0, tspeed)
 Turn (foot_l, z_axis, 0.34906584024429, tspeed)
end

function slightknee()
local mspeed = 50
local tspeed = math.rad(180)
Move (gp, x_axis, 0, mspeed)
Move (gp, y_axis, 0, mspeed)
Move (gp, z_axis, 0, mspeed)
Turn (gp, x_axis, 0, tspeed)
Turn (gp, y_axis, 0, tspeed)
Turn (gp, z_axis, 0, tspeed)
Move (cod, x_axis, 0, mspeed)
Move (cod, y_axis, -6, mspeed)
Move (cod, z_axis, 0, mspeed)
Turn (cod, x_axis, 0, tspeed)
Turn (cod, y_axis, 0, tspeed)
Turn (cod, z_axis, 0, tspeed)
Move (base, x_axis, 0, mspeed)
Move (base, y_axis, -1, mspeed)
Move (base, z_axis, 0, mspeed)
Turn (base, x_axis, 0.17453292012215, tspeed)
Turn (base, y_axis, 0, tspeed)
Turn (base, z_axis, 0, tspeed)
Move (head, x_axis, 0, mspeed)
Move (head, y_axis, 0, mspeed)
Move (head, z_axis, 0, mspeed)
Turn (head, x_axis, -0.34906584024429, tspeed)
Turn (head, y_axis, 0, tspeed)
Turn (head, z_axis, 0, tspeed)
Move (left, x_axis, 0, mspeed)
Move (left, y_axis, 0, mspeed)
Move (left, z_axis, 0, mspeed)
Turn (left, x_axis, 0, tspeed)
Turn (left, y_axis, 0, tspeed)
Turn (left, z_axis, 0.17453292012215, tspeed)
Move (l_arm, x_axis, 0, mspeed)
Move (l_arm, y_axis, 0, mspeed)
Move (l_arm, z_axis, 0, mspeed)
Turn (l_arm, x_axis, -0.34906584024429, tspeed)
Turn (l_arm, y_axis, 0, tspeed)
Turn (l_arm, z_axis, 0, tspeed)
Move (l_forearm, x_axis, 0, mspeed)
Move (l_forearm, y_axis, 0, mspeed)
Move (l_forearm, z_axis, 0, mspeed)
Turn (l_forearm, x_axis, -1.9198619127274, tspeed)
Turn (l_forearm, y_axis, 0, tspeed)
Turn (l_forearm, z_axis, 0, tspeed)
Move (right, x_axis, 0, mspeed)
Move (right, y_axis, 0, mspeed)
Move (right, z_axis, 0, mspeed)
Turn (right, x_axis, 0, tspeed)
Turn (right, y_axis, 0, tspeed)
Turn (right, z_axis, 0, tspeed)
Move (r_arm, x_axis, 0, mspeed)
Move (r_arm, y_axis, 0, mspeed)
Move (r_arm, z_axis, 0, mspeed)
Turn (r_arm, x_axis, 0, tspeed)
Turn (r_arm, y_axis, 0, tspeed)
Turn (r_arm, z_axis, -0.17453292012215, tspeed)
Move (r_forearm, x_axis, 0, mspeed)
Move (r_forearm, y_axis, 0, mspeed)
Move (r_forearm, z_axis, 0, mspeed)
Turn (r_forearm, x_axis, -1.9198620319366, tspeed)
Turn (r_forearm, y_axis, 0, tspeed)
Turn (r_forearm, z_axis, -0.17453292012215, tspeed)
Move (gun, x_axis, 0, mspeed)
Move (gun, y_axis, 0, mspeed)
Move (gun, z_axis, 0, mspeed)
Turn (gun, x_axis, -2.9802322387695e-008, tspeed)
Turn (gun, y_axis, 0, tspeed)
Turn (gun, z_axis, -0.17453292012215, tspeed)
Move (fire, x_axis, 0, mspeed)
Move (fire, y_axis, 0, mspeed)
Move (fire, z_axis, 0, mspeed)
Turn (fire, x_axis, 0, tspeed)
Turn (fire, y_axis, 0, tspeed)
Turn (fire, z_axis, 0, tspeed)
Move (right_l, x_axis, 0, mspeed)
Move (right_l, y_axis, 0, mspeed)
Move (right_l, z_axis, 0, mspeed)
Turn (right_l, x_axis, -0.69813168048859, tspeed)
Turn (right_l, y_axis, 0, tspeed)
Turn (right_l, z_axis, 0, tspeed)
Move (shin_r, x_axis, 0, mspeed)
Move (shin_r, y_axis, 0, mspeed)
Move (shin_r, z_axis, 0, mspeed)
Turn (shin_r, x_axis, 1.2217303514481, tspeed)
Turn (shin_r, y_axis, 0, tspeed)
Turn (shin_r, z_axis, 0, tspeed)
Move (foot_r, x_axis, 0, mspeed)
Move (foot_r, y_axis, 0, mspeed)
Move (foot_r, z_axis, 0, mspeed)
Turn (foot_r, x_axis, -0.69813168048859, tspeed)
Turn (foot_r, y_axis, 0, tspeed)
Turn (foot_r, z_axis, 0, tspeed)
Move (left_l, x_axis, 0, mspeed)
Move (left_l, y_axis, 0, mspeed)
Move (left_l, z_axis, 0, mspeed)
Turn (left_l, x_axis, -0.69813168048859, tspeed)
Turn (left_l, y_axis, 0, tspeed)
Turn (left_l, z_axis, 0, tspeed)
Move (shin_l, x_axis, 0, mspeed)
Move (shin_l, y_axis, 0, mspeed)
Move (shin_l, z_axis, 0, mspeed)
Turn (shin_l, x_axis, 1.2217303514481, tspeed)
Turn (shin_l, y_axis, 0, tspeed)
Turn (shin_l, z_axis, 0, tspeed)
Move (foot_l, x_axis, 0, mspeed)
Move (foot_l, y_axis, 0, mspeed)
Move (foot_l, z_axis, 0, mspeed)
Turn (foot_l, x_axis, -0.69813168048859, tspeed)
Turn (foot_l, y_axis, 0, tspeed)
Turn (foot_l, z_axis, 0, tspeed)
end

function salto1(mspeed, tspeed)
 Move (gp, x_axis, 0, mspeed)
 Move (gp, y_axis, 9, mspeed)
 Move (gp, z_axis, 0, mspeed)
 Turn (gp, x_axis, 0, tspeed)
 Turn (gp, y_axis, 0, tspeed)
 Turn (gp, z_axis, 0, tspeed)
 Move (cod, x_axis, 0, mspeed)
 Move (cod, y_axis, 0, mspeed)
 Move (cod, z_axis, 0, mspeed)
 Turn (cod, x_axis, 0.69813168048859, tspeed)
 Turn (cod, y_axis, 0, tspeed)
 Turn (cod, z_axis, 0, tspeed)
 Move (base, x_axis, 0, mspeed)
 Move (base, y_axis, 0, mspeed)
 Move (base, z_axis, 0, mspeed)
 Turn (base, x_axis, 0.52359879016876, tspeed)
 Turn (base, y_axis, 0, tspeed)
 Turn (base, z_axis, 0, tspeed)
 Move (head, x_axis, 0, mspeed)
 Move (head, y_axis, 0, mspeed)
 Move (head, z_axis, 0, mspeed)
 Turn (head, x_axis, 0.52359879016876, tspeed)
 Turn (head, y_axis, 0, tspeed)
 Turn (head, z_axis, 0, tspeed)
 Move (left, x_axis, 0, mspeed)
 Move (left, y_axis, 0, mspeed)
 Move (left, z_axis, 0, mspeed)
 Turn (left, x_axis, -0.52359879016876, tspeed)
 Turn (left, y_axis, 0, tspeed)
 Turn (left, z_axis, 0, tspeed)
 Move (l_arm, x_axis, 0, mspeed)
 Move (l_arm, y_axis, 0, mspeed)
 Move (l_arm, z_axis, 0, mspeed)
 Turn (l_arm, x_axis, 0.34906581044197, tspeed)
 Turn (l_arm, y_axis, 0, tspeed)
 Turn (l_arm, z_axis, 0, tspeed)
 Move (l_forearm, x_axis, 0, mspeed)
 Move (l_forearm, y_axis, 0, mspeed)
 Move (l_forearm, z_axis, 0, mspeed)
 Turn (l_forearm, x_axis, -1.0471974611282, tspeed)
 Turn (l_forearm, y_axis, 0, tspeed)
 Turn (l_forearm, z_axis, 0, tspeed)
 Move (right, x_axis, 0, mspeed)
 Move (right, y_axis, 0, mspeed)
 Move (right, z_axis, 0, mspeed)
 Turn (right, x_axis, 0, tspeed)
 Turn (right, y_axis, 0, tspeed)
 Turn (right, z_axis, 0, tspeed)
 Move (r_arm, x_axis, 0, mspeed)
 Move (r_arm, y_axis, 0, mspeed)
 Move (r_arm, z_axis, 0, mspeed)
 Turn (r_arm, x_axis, -0.17453292012215, tspeed)
 Turn (r_arm, y_axis, 0, tspeed)
 Turn (r_arm, z_axis, 0, tspeed)
 Move (r_forearm, x_axis, 0, mspeed)
 Move (r_forearm, y_axis, 0, mspeed)
 Move (r_forearm, z_axis, 0, mspeed)
 Turn (r_forearm, x_axis, -1.2217303514481, tspeed)
 Turn (r_forearm, y_axis, 0, tspeed)
 Turn (r_forearm, z_axis, 0, tspeed)
 Move (gun, x_axis, 0, mspeed)
 Move (gun, y_axis, 0, mspeed)
 Move (gun, z_axis, 0, mspeed)
 Turn (gun, x_axis, 0, tspeed)
 Turn (gun, y_axis, 0, tspeed)
 Turn (gun, z_axis, 0, tspeed)
 Move (fire, x_axis, 0, mspeed)
 Move (fire, y_axis, 0, mspeed)
 Move (fire, z_axis, 0, mspeed)
 Turn (fire, x_axis, 0, tspeed)
 Turn (fire, y_axis, 0, tspeed)
 Turn (fire, z_axis, 0, tspeed)
 Move (right_l, x_axis, 0, mspeed)
 Move (right_l, y_axis, 0, mspeed)
 Move (right_l, z_axis, 0, mspeed)
 Turn (right_l, x_axis, -1.7453290224075, tspeed)
 Turn (right_l, y_axis, 0, tspeed)
 Turn (right_l, z_axis, 0, tspeed)
 Move (shin_r, x_axis, 0, mspeed)
 Move (shin_r, y_axis, 0, mspeed)
 Move (shin_r, z_axis, 0, mspeed)
 Turn (shin_r, x_axis, 1.7453290224075, tspeed)
 Turn (shin_r, y_axis, 0, tspeed)
 Turn (shin_r, z_axis, 0, tspeed)
 Move (foot_r, x_axis, 0, mspeed)
 Move (foot_r, y_axis, 0, mspeed)
 Move (foot_r, z_axis, 0, mspeed)
 Turn (foot_r, x_axis, 0.69813168048859, tspeed)
 Turn (foot_r, y_axis, 0, tspeed)
 Turn (foot_r, z_axis, 0, tspeed)
 Move (left_l, x_axis, 0, mspeed)
 Move (left_l, y_axis, 0, mspeed)
 Move (left_l, z_axis, 0, mspeed)
 Turn (left_l, x_axis, -1.9198619127274, tspeed)
 Turn (left_l, y_axis, 0, tspeed)
 Turn (left_l, z_axis, 0, tspeed)
 Move (shin_l, x_axis, 0, mspeed)
 Move (shin_l, y_axis, 0, mspeed)
 Move (shin_l, z_axis, 0, mspeed)
 Turn (shin_l, x_axis, 1.9198619127274, tspeed)
 Turn (shin_l, y_axis, 0, tspeed)
 Turn (shin_l, z_axis, 0, tspeed)
 Move (foot_l, x_axis, 0, mspeed)
 Move (foot_l, y_axis, 0, mspeed)
 Move (foot_l, z_axis, 0, mspeed)
 Turn (foot_l, x_axis, 0, tspeed)
 Turn (foot_l, y_axis, 0, tspeed)
 Turn (foot_l, z_axis, 0, tspeed)
end

function salto2 (mspeed,tspeed)
 Move (gp, x_axis, 0, mspeed)
 Move (gp, y_axis, 9, mspeed)
 Move (gp, z_axis, 0, mspeed)
 Turn (gp, x_axis, 0, tspeed)
 Turn (gp, y_axis, 0, tspeed)
 Turn (gp, z_axis, 0, tspeed)
 Move (cod, x_axis, 0, mspeed)
 Move (cod, y_axis, 5, mspeed)
 Move (cod, z_axis, 9, mspeed)
 Turn (cod, x_axis, 2.6179935932159, tspeed)
 Turn (cod, y_axis, 0, tspeed)
 Turn (cod, z_axis, -0.17453292012215, tspeed)
 Move (base, x_axis, 0, mspeed)
 Move (base, y_axis, 0, mspeed)
 Move (base, z_axis, 0, mspeed)
 Turn (base, x_axis, 0.87266457080841, tspeed)
 Turn (base, y_axis, 0, tspeed)
 Turn (base, z_axis, 0, tspeed)
 Move (head, x_axis, 0, mspeed)
 Move (head, y_axis, 0, mspeed)
 Move (head, z_axis, 0, mspeed)
 Turn (head, x_axis, 0.52359879016876, tspeed)
 Turn (head, y_axis, 0, tspeed)
 Turn (head, z_axis, 0, tspeed)
 Move (left, x_axis, 0, mspeed)
 Move (left, y_axis, 0, mspeed)
 Move (left, z_axis, 0, mspeed)
 Turn (left, x_axis, -0.52359879016876, tspeed)
 Turn (left, y_axis, 0, tspeed)
 Turn (left, z_axis, 0, tspeed)
 Move (l_arm, x_axis, 0, mspeed)
 Move (l_arm, y_axis, 0, mspeed)
 Move (l_arm, z_axis, 0, mspeed)
 Turn (l_arm, x_axis, 0.34906581044197, tspeed)
 Turn (l_arm, y_axis, 0, tspeed)
 Turn (l_arm, z_axis, 0, tspeed)
 Move (l_forearm, x_axis, 0, mspeed)
 Move (l_forearm, y_axis, 0, mspeed)
 Move (l_forearm, z_axis, 0, mspeed)
 Turn (l_forearm, x_axis, -1.0471974611282, tspeed)
 Turn (l_forearm, y_axis, 0, tspeed)
 Turn (l_forearm, z_axis, 0, tspeed)
 Move (right, x_axis, 0, mspeed)
 Move (right, y_axis, 0, mspeed)
 Move (right, z_axis, 0, mspeed)
 Turn (right, x_axis, 0, tspeed)
 Turn (right, y_axis, 0, tspeed)
 Turn (right, z_axis, 0, tspeed)
 Move (r_arm, x_axis, 0, mspeed)
 Move (r_arm, y_axis, 0, mspeed)
 Move (r_arm, z_axis, 0, mspeed)
 Turn (r_arm, x_axis, 0, tspeed)
 Turn (r_arm, y_axis, 0, tspeed)
 Turn (r_arm, z_axis, 0, tspeed)
 Move (r_forearm, x_axis, 0, mspeed)
 Move (r_forearm, y_axis, 0, mspeed)
 Move (r_forearm, z_axis, 0, mspeed)
 Turn (r_forearm, x_axis, -1.0471974611282, tspeed)
 Turn (r_forearm, y_axis, 0, tspeed)
 Turn (r_forearm, z_axis, 0, tspeed)
 Move (gun, x_axis, 0, mspeed)
 Move (gun, y_axis, 0, mspeed)
 Move (gun, z_axis, 0, mspeed)
 Turn (gun, x_axis, 0, tspeed)
 Turn (gun, y_axis, 0, tspeed)
 Turn (gun, z_axis, 0, tspeed)
 Move (fire, x_axis, 0, mspeed)
 Move (fire, y_axis, 0, mspeed)
 Move (fire, z_axis, 0, mspeed)
 Turn (fire, x_axis, 0, tspeed)
 Turn (fire, y_axis, 0, tspeed)
 Turn (fire, z_axis, 0, tspeed)
 Move (right_l, x_axis, 0, mspeed)
 Move (right_l, y_axis, 0, mspeed)
 Move (right_l, z_axis, 0, mspeed)
 Turn (right_l, x_axis, -1.7453290224075, tspeed)
 Turn (right_l, y_axis, 0, tspeed)
 Turn (right_l, z_axis, 0, tspeed)
 Move (shin_r, x_axis, 0, mspeed)
 Move (shin_r, y_axis, 0, mspeed)
 Move (shin_r, z_axis, 0, mspeed)
 Turn (shin_r, x_axis, 1.7453290224075, tspeed)
 Turn (shin_r, y_axis, 0, tspeed)
 Turn (shin_r, z_axis, 0.17453292012215, tspeed)
 Move (foot_r, x_axis, 0, mspeed)
 Move (foot_r, y_axis, 0, mspeed)
 Move (foot_r, z_axis, 0, mspeed)
 Turn (foot_r, x_axis, 0.52359879016876, tspeed)
 Turn (foot_r, y_axis, 0, tspeed)
 Turn (foot_r, z_axis, 0, tspeed)
 Move (left_l, x_axis, 0, mspeed)
 Move (left_l, y_axis, 0, mspeed)
 Move (left_l, z_axis, 0, mspeed)
 Turn (left_l, x_axis, -1.9198619127274, tspeed)
 Turn (left_l, y_axis, 0, tspeed)
 Turn (left_l, z_axis, 0, tspeed)
 Move (shin_l, x_axis, 0, mspeed)
 Move (shin_l, y_axis, 0, mspeed)
 Move (shin_l, z_axis, 0, mspeed)
 Turn (shin_l, x_axis, 2.0943949222565, tspeed)
 Turn (shin_l, y_axis, 0, tspeed)
 Turn (shin_l, z_axis, 0, tspeed)
 Move (foot_l, x_axis, 0, mspeed)
 Move (foot_l, y_axis, 0, mspeed)
 Move (foot_l, z_axis, 0, mspeed)
 Turn (foot_l, x_axis, -0.17453292012215, tspeed)
 Turn (foot_l, y_axis, 0, tspeed)
 Turn (foot_l, z_axis, 0, tspeed)
end


function salto3 (mspeed,tspeed)
Move (gp, x_axis, 0, mspeed)
Move (gp, y_axis, 9, mspeed)
Move (gp, z_axis, 0, mspeed)
Turn (gp, x_axis, 0, tspeed)
Turn (gp, y_axis, 0, tspeed)
Turn (gp, z_axis, 0, tspeed)
Move (cod, x_axis, 0, mspeed)
Move (cod, y_axis, -4, mspeed)
Move (cod, z_axis, 10, mspeed)
Turn (cod, x_axis, 0.8726646900177, tspeed)
Turn (cod, y_axis, 0, tspeed)
Turn (cod, z_axis, -0.17453292012215, tspeed)
Move (base, x_axis, 0, mspeed)
Move (base, y_axis, 0, mspeed)
Move (base, z_axis, 0, mspeed)
Turn (base, x_axis, -0.17453289031982, tspeed)
Turn (base, y_axis, 0, tspeed)
Turn (base, z_axis, 0, tspeed)
Move (head, x_axis, 0, mspeed)
Move (head, y_axis, 0, mspeed)
Move (head, z_axis, 0, mspeed)
Turn (head, x_axis, -0.52359873056412, tspeed)
Turn (head, y_axis, 0, tspeed)
Turn (head, z_axis, 0, tspeed)
Move (left, x_axis, 0, mspeed)
Move (left, y_axis, 0, mspeed)
Move (left, z_axis, 0, mspeed)
Turn (left, x_axis, -0.52359879016876, tspeed)
Turn (left, y_axis, 0, tspeed)
Turn (left, z_axis, 0, tspeed)
Move (l_arm, x_axis, 0, mspeed)
Move (l_arm, y_axis, 0, mspeed)
Move (l_arm, z_axis, 0, mspeed)
Turn (l_arm, x_axis, 0.34906581044197, tspeed)
Turn (l_arm, y_axis, 0, tspeed)
Turn (l_arm, z_axis, 0, tspeed)
Move (l_forearm, x_axis, 0, mspeed)
Move (l_forearm, y_axis, 0, mspeed)
Move (l_forearm, z_axis, 0, mspeed)
Turn (l_forearm, x_axis, -1.0471974611282, tspeed)
Turn (l_forearm, y_axis, 0, tspeed)
Turn (l_forearm, z_axis, 0, tspeed)
Move (right, x_axis, 0, mspeed)
Move (right, y_axis, 0, mspeed)
Move (right, z_axis, 0, mspeed)
Turn (right, x_axis, 0, tspeed)
Turn (right, y_axis, 0, tspeed)
Turn (right, z_axis, 0, tspeed)
Move (r_arm, x_axis, 0, mspeed)
Move (r_arm, y_axis, 0, mspeed)
Move (r_arm, z_axis, 0, mspeed)
Turn (r_arm, x_axis, 0.17453292012215, tspeed)
Turn (r_arm, y_axis, 0, tspeed)
Turn (r_arm, z_axis, 0, tspeed)
Move (r_forearm, x_axis, 0, mspeed)
Move (r_forearm, y_axis, 0, mspeed)
Move (r_forearm, z_axis, 0, mspeed)
Turn (r_forearm, x_axis, -0.34906587004662, tspeed)
Turn (r_forearm, y_axis, 0, tspeed)
Turn (r_forearm, z_axis, 0, tspeed)
Move (gun, x_axis, 0, mspeed)
Move (gun, y_axis, 0, mspeed)
Move (gun, z_axis, 0, mspeed)
Turn (gun, x_axis, 0, tspeed)
Turn (gun, y_axis, 0, tspeed)
Turn (gun, z_axis, 0, tspeed)
Move (fire, x_axis, 0, mspeed)
Move (fire, y_axis, 0, mspeed)
Move (fire, z_axis, 0, mspeed)
Turn (fire, x_axis, 0, tspeed)
Turn (fire, y_axis, 0, tspeed)
Turn (fire, z_axis, 0, tspeed)
Move (right_l, x_axis, 0, mspeed)
Move (right_l, y_axis, 0, mspeed)
Move (right_l, z_axis, 0, mspeed)
Turn (right_l, x_axis, -0.52359879016876, tspeed)
Turn (right_l, y_axis, 0, tspeed)
Turn (right_l, z_axis, 0, tspeed)
Move (shin_r, x_axis, 0, mspeed)
Move (shin_r, y_axis, 0, mspeed)
Move (shin_r, z_axis, 0, mspeed)
Turn (shin_r, x_axis, 0.69813168048859, tspeed)
Turn (shin_r, y_axis, 0, tspeed)
Turn (shin_r, z_axis, 0.17453292012215, tspeed)
Move (foot_r, x_axis, 0, mspeed)
Move (foot_r, y_axis, 0, mspeed)
Move (foot_r, z_axis, 0, mspeed)
Turn (foot_r, x_axis, 0.52359879016876, tspeed)
Turn (foot_r, y_axis, 0, tspeed)
Turn (foot_r, z_axis, 0, tspeed)
Move (left_l, x_axis, 0, mspeed)
Move (left_l, y_axis, 0, mspeed)
Move (left_l, z_axis, 0, mspeed)
Turn (left_l, x_axis, -0.69813179969788, tspeed)
Turn (left_l, y_axis, 0, tspeed)
Turn (left_l, z_axis, 0, tspeed)
Move (shin_l, x_axis, 0, mspeed)
Move (shin_l, y_axis, 0, mspeed)
Move (shin_l, z_axis, 0, mspeed)
Turn (shin_l, x_axis, 1.2217304706573, tspeed)
Turn (shin_l, y_axis, 0, tspeed)
Turn (shin_l, z_axis, 0, tspeed)
Move (foot_l, x_axis, 0, mspeed)
Move (foot_l, y_axis, 0, mspeed)
Move (foot_l, z_axis, 0, mspeed)
Turn (foot_l, x_axis, 0.34906584024429, tspeed)
Turn (foot_l, y_axis, 0, tspeed)
Turn (foot_l, z_axis, 0, tspeed)
end

function salto4(mspeed,tspeed)
 Move (gp, x_axis, 0, mspeed)
 Move (gp, y_axis, 9, mspeed)
 Move (gp, z_axis, 0, mspeed)
 Turn (gp, x_axis, 0, tspeed)
 Turn (gp, y_axis, 0, tspeed)
 Turn (gp, z_axis, 0, tspeed)
 Move (cod, x_axis, 0, mspeed)
 Move (cod, y_axis, -14, mspeed)
 Move (cod, z_axis, 9, mspeed)
 Turn (cod, x_axis, 1.4901161193848e-007, tspeed)
 Turn (cod, y_axis, 0, tspeed)
 Turn (cod, z_axis, -2.9802322387695e-008, tspeed)
 Move (base, x_axis, 0, mspeed)
 Move (base, y_axis, 0, mspeed)
 Move (base, z_axis, 0, mspeed)
 Turn (base, x_axis, 0.34906587004662, tspeed)
 Turn (base, y_axis, -0.17453292012215, tspeed)
 Turn (base, z_axis, 0, tspeed)
 Move (head, x_axis, 0, mspeed)
 Move (head, y_axis, 0, mspeed)
 Move (head, z_axis, 0, mspeed)
 Turn (head, x_axis, -0.52359873056412, tspeed)
 Turn (head, y_axis, 0, tspeed)
 Turn (head, z_axis, -0.17453292012215, tspeed)
 Move (left, x_axis, 0, mspeed)
 Move (left, y_axis, 0, mspeed)
 Move (left, z_axis, 0, mspeed)
 Turn (left, x_axis, -0.52359879016876, tspeed)
 Turn (left, y_axis, 0, tspeed)
 Turn (left, z_axis, 0, tspeed)
 Move (l_arm, x_axis, 0, mspeed)
 Move (l_arm, y_axis, 0, mspeed)
 Move (l_arm, z_axis, 0, mspeed)
 Turn (l_arm, x_axis, 0.17453289031982, tspeed)
 Turn (l_arm, y_axis, 0, tspeed)
 Turn (l_arm, z_axis, 0, tspeed)
 Move (l_forearm, x_axis, 0, mspeed)
 Move (l_forearm, y_axis, 0, mspeed)
 Move (l_forearm, z_axis, 0, mspeed)
 Turn (l_forearm, x_axis, -0.34906587004662, tspeed)
 Turn (l_forearm, y_axis, 0, tspeed)
 Turn (l_forearm, z_axis, 0, tspeed)
 Move (right, x_axis, 0, mspeed)
 Move (right, y_axis, 0, mspeed)
 Move (right, z_axis, 0, mspeed)
 Turn (right, x_axis, 0, tspeed)
 Turn (right, y_axis, 0, tspeed)
 Turn (right, z_axis, 0, tspeed)
 Move (r_arm, x_axis, 0, mspeed)
 Move (r_arm, y_axis, 0, mspeed)
 Move (r_arm, z_axis, 0, mspeed)
 Turn (r_arm, x_axis, 0, tspeed)
 Turn (r_arm, y_axis, 0, tspeed)
 Turn (r_arm, z_axis, -0.17453292012215, tspeed)
 Move (r_forearm, x_axis, 0, mspeed)
 Move (r_forearm, y_axis, 0, mspeed)
 Move (r_forearm, z_axis, 0, mspeed)
 Turn (r_forearm, x_axis, -0.34906587004662, tspeed)
 Turn (r_forearm, y_axis, 0, tspeed)
 Turn (r_forearm, z_axis, 0, tspeed)
 Move (gun, x_axis, 0, mspeed)
 Move (gun, y_axis, 0, mspeed)
 Move (gun, z_axis, 0, mspeed)
 Turn (gun, x_axis, 0, tspeed)
 Turn (gun, y_axis, 0, tspeed)
 Turn (gun, z_axis, 0, tspeed)
 Move (fire, x_axis, 0, mspeed)
 Move (fire, y_axis, 0, mspeed)
 Move (fire, z_axis, 0, mspeed)
 Turn (fire, x_axis, 0, tspeed)
 Turn (fire, y_axis, 0, tspeed)
 Turn (fire, z_axis, 0, tspeed)
 Move (right_l, x_axis, 0, mspeed)
 Move (right_l, y_axis, 0, mspeed)
 Move (right_l, z_axis, 0, mspeed)
 Turn (right_l, x_axis, -0.52359879016876, tspeed)
 Turn (right_l, y_axis, 0, tspeed)
 Turn (right_l, z_axis, -0.34906584024429, tspeed)
 Move (shin_r, x_axis, 0, mspeed)
 Move (shin_r, y_axis, 0, mspeed)
 Move (shin_r, z_axis, 0, mspeed)
 Turn (shin_r, x_axis, 0.34906587004662, tspeed)
 Turn (shin_r, y_axis, 0, tspeed)
 Turn (shin_r, z_axis, 0.17453292012215, tspeed)
 Move (foot_r, x_axis, 0, mspeed)
 Move (foot_r, y_axis, 0, mspeed)
 Move (foot_r, z_axis, 0, mspeed)
 Turn (foot_r, x_axis, 0.52359879016876, tspeed)
 Turn (foot_r, y_axis, 0, tspeed)
 Turn (foot_r, z_axis, 0, tspeed)
 Move (left_l, x_axis, 0, mspeed)
 Move (left_l, y_axis, 0, mspeed)
 Move (left_l, z_axis, 0, mspeed)
 Turn (left_l, x_axis, -0.69813179969788, tspeed)
 Turn (left_l, y_axis, 0, tspeed)
 Turn (left_l, z_axis, 0, tspeed)
 Move (shin_l, x_axis, 0, mspeed)
 Move (shin_l, y_axis, 0, mspeed)
 Move (shin_l, z_axis, 0, mspeed)
 Turn (shin_l, x_axis, 0.69813179969788, tspeed)
 Turn (shin_l, y_axis, 0, tspeed)
 Turn (shin_l, z_axis, 0, tspeed)
 Move (foot_l, x_axis, 0, mspeed)
 Move (foot_l, y_axis, 0, mspeed)
 Move (foot_l, z_axis, 0, mspeed)
 Turn (foot_l, x_axis, -0.34906581044197, tspeed)
 Turn (foot_l, y_axis, 0, tspeed)
 Turn (foot_l, z_axis, 0, tspeed)
end


function salto5(mspeed,tspeed)
 Move (gp, x_axis, 0, mspeed)
 Move (gp, y_axis, 0, mspeed)
 Move (gp, z_axis, 0, mspeed)
 Turn (gp, x_axis, 0, tspeed)
 Turn (gp, y_axis, 0, tspeed)
 Turn (gp, z_axis, 0, tspeed)
 Move (cod, x_axis, 0, mspeed)
 Move (cod, y_axis, 29.000003814697, mspeed)
 Move (cod, z_axis, 0, mspeed)
 Turn (cod, x_axis, 10.471974372864, tspeed)
 Turn (cod, y_axis, 0, tspeed)
 Turn (cod, z_axis, 0, tspeed)
 Move (base, x_axis, 0, mspeed)
 Move (base, y_axis, 0, mspeed)
 Move (base, z_axis, 0, mspeed)
 Turn (base, x_axis, 1.0471974611282, tspeed)
 Turn (base, y_axis, 0, tspeed)
 Turn (base, z_axis, 0, tspeed)
 Move (head, x_axis, 0, mspeed)
 Move (head, y_axis, 0, mspeed)
 Move (head, z_axis, 0, mspeed)
 Turn (head, x_axis, 0.17453292012215, tspeed)
 Turn (head, y_axis, 0, tspeed)
 Turn (head, z_axis, 0, tspeed)
 Move (left, x_axis, 0, mspeed)
 Move (left, y_axis, 0, mspeed)
 Move (left, z_axis, 0, mspeed)
 Turn (left, x_axis, 0, tspeed)
 Turn (left, y_axis, 0, tspeed)
 Turn (left, z_axis, 0, tspeed)
 Move (l_arm, x_axis, 0, mspeed)
 Move (l_arm, y_axis, 0, mspeed)
 Move (l_arm, z_axis, 0, mspeed)
 Turn (l_arm, x_axis, 0, tspeed)
 Turn (l_arm, y_axis, 0, tspeed)
 Turn (l_arm, z_axis, 0, tspeed)
 Move (l_forearm, x_axis, 0, mspeed)
 Move (l_forearm, y_axis, 0, mspeed)
 Move (l_forearm, z_axis, 0, mspeed)
 Turn (l_forearm, x_axis, 0, tspeed)
 Turn (l_forearm, y_axis, 0, tspeed)
 Turn (l_forearm, z_axis, 0, tspeed)
 Move (right, x_axis, 0, mspeed)
 Move (right, y_axis, 0, mspeed)
 Move (right, z_axis, 0, mspeed)
 Turn (right, x_axis, 0, tspeed)
 Turn (right, y_axis, 0, tspeed)
 Turn (right, z_axis, 0, tspeed)
 Move (r_arm, x_axis, 0, mspeed)
 Move (r_arm, y_axis, 0, mspeed)
 Move (r_arm, z_axis, 0, mspeed)
 Turn (r_arm, x_axis, -0.17453292012215, tspeed)
 Turn (r_arm, y_axis, 0, tspeed)
 Turn (r_arm, z_axis, 0, tspeed)
 Move (r_forearm, x_axis, 0, mspeed)
 Move (r_forearm, y_axis, 0, mspeed)
 Move (r_forearm, z_axis, 0, mspeed)
 Turn (r_forearm, x_axis, -0.34906584024429, tspeed)
 Turn (r_forearm, y_axis, 0, tspeed)
 Turn (r_forearm, z_axis, 0, tspeed)
 Move (gun, x_axis, 0, mspeed)
 Move (gun, y_axis, 0, mspeed)
 Move (gun, z_axis, 0, mspeed)
 Turn (gun, x_axis, 0, tspeed)
 Turn (gun, y_axis, 0, tspeed)
 Turn (gun, z_axis, 0, tspeed)
 Move (fire, x_axis, 0, mspeed)
 Move (fire, y_axis, 0, mspeed)
 Move (fire, z_axis, 0, mspeed)
 Turn (fire, x_axis, 0, tspeed)
 Turn (fire, y_axis, 0, tspeed)
 Turn (fire, z_axis, 0, tspeed)
 Move (right_l, x_axis, 0, mspeed)
 Move (right_l, y_axis, 0, mspeed)
 Move (right_l, z_axis, 0, mspeed)
 Turn (right_l, x_axis, -0.87266457080841, tspeed)
 Turn (right_l, y_axis, 0, tspeed)
 Turn (right_l, z_axis, 0, tspeed)
 Move (shin_r, x_axis, 0, mspeed)
 Move (shin_r, y_axis, 0, mspeed)
 Move (shin_r, z_axis, 0, mspeed)
 Turn (shin_r, x_axis, 1.9198619127274, tspeed)
 Turn (shin_r, y_axis, 0, tspeed)
 Turn (shin_r, z_axis, 0, tspeed)
 Move (foot_r, x_axis, 0, mspeed)
 Move (foot_r, y_axis, 0, mspeed)
 Move (foot_r, z_axis, 0, mspeed)
 Turn (foot_r, x_axis, 0, tspeed)
 Turn (foot_r, y_axis, 0, tspeed)
 Turn (foot_r, z_axis, 0, tspeed)
 Move (left_l, x_axis, 0, mspeed)
 Move (left_l, y_axis, 0, mspeed)
 Move (left_l, z_axis, 0, mspeed)
 Turn (left_l, x_axis, -1.2217303514481, tspeed)
 Turn (left_l, y_axis, 0, tspeed)
 Turn (left_l, z_axis, 0, tspeed)
 Move (shin_l, x_axis, 0, mspeed)
 Move (shin_l, y_axis, 0, mspeed)
 Move (shin_l, z_axis, 0, mspeed)
 Turn (shin_l, x_axis, 2.0943949222565, tspeed)
 Turn (shin_l, y_axis, 0, tspeed)
 Turn (shin_l, z_axis, 0, tspeed)
 Move (foot_l, x_axis, 0, mspeed)
 Move (foot_l, y_axis, 0, mspeed)
 Move (foot_l, z_axis, 0, mspeed)
 Turn (foot_l, x_axis, 0, tspeed)
 Turn (foot_l, y_axis, 0, tspeed)
 Turn (foot_l, z_axis, 0, tspeed)

end

function salto6(mspeed,tspeed)
 Move (gp, x_axis, 0, mspeed)
 Move (gp, y_axis, 0, mspeed)
 Move (gp, z_axis, 0, mspeed)
 Turn (gp, x_axis, 0, tspeed)
 Turn (gp, y_axis, 0, tspeed)
 Turn (gp, z_axis, 0, tspeed)
 Move (cod, x_axis, 0, mspeed)
 Move (cod, y_axis, 19.000003814697, mspeed)
 Move (cod, z_axis, -1, mspeed)
 Turn (cod, x_axis, 11.344638824463, tspeed)
 Turn (cod, y_axis, 0, tspeed)
 Turn (cod, z_axis, 0, tspeed)
 Move (base, x_axis, 0, mspeed)
 Move (base, y_axis, 0, mspeed)
 Move (base, z_axis, 0, mspeed)
 Turn (base, x_axis, 1.0471974611282, tspeed)
 Turn (base, y_axis, 0, tspeed)
 Turn (base, z_axis, 0, tspeed)
 Move (head, x_axis, 0, mspeed)
 Move (head, y_axis, 0, mspeed)
 Move (head, z_axis, 0, mspeed)
 Turn (head, x_axis, 0.17453292012215, tspeed)
 Turn (head, y_axis, 0, tspeed)
 Turn (head, z_axis, 0, tspeed)
 Move (left, x_axis, 0, mspeed)
 Move (left, y_axis, 0, mspeed)
 Move (left, z_axis, 0, mspeed)
 Turn (left, x_axis, 0, tspeed)
 Turn (left, y_axis, 0, tspeed)
 Turn (left, z_axis, 0, tspeed)
 Move (l_arm, x_axis, 0, mspeed)
 Move (l_arm, y_axis, 0, mspeed)
 Move (l_arm, z_axis, 0, mspeed)
 Turn (l_arm, x_axis, 0, tspeed)
 Turn (l_arm, y_axis, 0, tspeed)
 Turn (l_arm, z_axis, 0, tspeed)
 Move (l_forearm, x_axis, 0, mspeed)
 Move (l_forearm, y_axis, 0, mspeed)
 Move (l_forearm, z_axis, 0, mspeed)
 Turn (l_forearm, x_axis, 0, tspeed)
 Turn (l_forearm, y_axis, 0, tspeed)
 Turn (l_forearm, z_axis, 0, tspeed)
 Move (right, x_axis, 0, mspeed)
 Move (right, y_axis, 0, mspeed)
 Move (right, z_axis, 0, mspeed)
 Turn (right, x_axis, 0, tspeed)
 Turn (right, y_axis, 0, tspeed)
 Turn (right, z_axis, 0, tspeed)
 Move (r_arm, x_axis, 0, mspeed)
 Move (r_arm, y_axis, 0, mspeed)
 Move (r_arm, z_axis, 0, mspeed)
 Turn (r_arm, x_axis, -0.17453292012215, tspeed)
 Turn (r_arm, y_axis, 0, tspeed)
 Turn (r_arm, z_axis, 0, tspeed)
 Move (r_forearm, x_axis, 0, mspeed)
 Move (r_forearm, y_axis, 0, mspeed)
 Move (r_forearm, z_axis, 0, mspeed)
 Turn (r_forearm, x_axis, -0.34906584024429, tspeed)
 Turn (r_forearm, y_axis, 0, tspeed)
 Turn (r_forearm, z_axis, 0, tspeed)
 Move (gun, x_axis, 0, mspeed)
 Move (gun, y_axis, 0, mspeed)
 Move (gun, z_axis, 0, mspeed)
 Turn (gun, x_axis, 0, tspeed)
 Turn (gun, y_axis, 0, tspeed)
 Turn (gun, z_axis, 0, tspeed)
 Move (fire, x_axis, 0, mspeed)
 Move (fire, y_axis, 0, mspeed)
 Move (fire, z_axis, 0, mspeed)
 Turn (fire, x_axis, 0, tspeed)
 Turn (fire, y_axis, 0, tspeed)
 Turn (fire, z_axis, 0, tspeed)
 Move (right_l, x_axis, 0, mspeed)
 Move (right_l, y_axis, 0, mspeed)
 Move (right_l, z_axis, 0, mspeed)
 Turn (right_l, x_axis, -0.87266457080841, tspeed)
 Turn (right_l, y_axis, 0, tspeed)
 Turn (right_l, z_axis, 0, tspeed)
 Move (shin_r, x_axis, 0, mspeed)
 Move (shin_r, y_axis, 0, mspeed)
 Move (shin_r, z_axis, 0, mspeed)
 Turn (shin_r, x_axis, 1.9198619127274, tspeed)
 Turn (shin_r, y_axis, 0, tspeed)
 Turn (shin_r, z_axis, 0, tspeed)
 Move (foot_r, x_axis, 0, mspeed)
 Move (foot_r, y_axis, 0, mspeed)
 Move (foot_r, z_axis, 0, mspeed)
 Turn (foot_r, x_axis, 0, tspeed)
 Turn (foot_r, y_axis, 0, tspeed)
 Turn (foot_r, z_axis, 0, tspeed)
 Move (left_l, x_axis, 0, mspeed)
 Move (left_l, y_axis, 0, mspeed)
 Move (left_l, z_axis, 0, mspeed)
 Turn (left_l, x_axis, -1.2217303514481, tspeed)
 Turn (left_l, y_axis, 0, tspeed)
 Turn (left_l, z_axis, 0, tspeed)
 Move (shin_l, x_axis, 0, mspeed)
 Move (shin_l, y_axis, 0, mspeed)
 Move (shin_l, z_axis, 0, mspeed)
 Turn (shin_l, x_axis, 2.0943949222565, tspeed)
 Turn (shin_l, y_axis, 0, tspeed)
 Turn (shin_l, z_axis, 0, tspeed)
 Move (foot_l, x_axis, 0, mspeed)
 Move (foot_l, y_axis, 0, mspeed)
 Move (foot_l, z_axis, 0, mspeed)
 Turn (foot_l, x_axis, 0, tspeed)
 Turn (foot_l, y_axis, 0, tspeed)
 Turn (foot_l, z_axis, 0, tspeed)
end



function salut (mspeed,tspeed)
Move (gp, x_axis, 0, mspeed)
Move (gp, y_axis, 0, mspeed)
Move (gp, z_axis, 0, mspeed)
Turn (gp, x_axis, 0, tspeed)
Turn (gp, y_axis, 0, tspeed)
Turn (gp, z_axis, 0, tspeed)
Move (cod, x_axis, 0, mspeed)
Move (cod, y_axis, 0, mspeed)
Move (cod, z_axis, 0, mspeed)
Turn (cod, x_axis, 0, tspeed)
Turn (cod, y_axis, 0, tspeed)
Turn (cod, z_axis, 0, tspeed)
Move (base, x_axis, 0, mspeed)
Move (base, y_axis, 0, mspeed)
Move (base, z_axis, 0, mspeed)
Turn (base, x_axis, 0, tspeed)
Turn (base, y_axis, 0, tspeed)
Turn (base, z_axis, 0, tspeed)
Move (head, x_axis, 0, mspeed)
Move (head, y_axis, 0, mspeed)
Move (head, z_axis, 0, mspeed)
Turn (head, x_axis, 0.17453292012215, tspeed)
Turn (head, y_axis, 0.17453292012215, tspeed)
Turn (head, z_axis, -0.17453292012215, tspeed)
Move (left, x_axis, 0, mspeed)
Move (left, y_axis, 0, mspeed)
Move (left, z_axis, 0, mspeed)
Turn (left, x_axis, -1.3962632417679, tspeed)
Turn (left, y_axis, -0.34906584024429, tspeed)
Turn (left, z_axis, 0.17453289031982, tspeed)
Move (l_arm, x_axis, 0, mspeed)
Move (l_arm, y_axis, 0, mspeed)
Move (l_arm, z_axis, 0, mspeed)
Turn (l_arm, x_axis, 0.17453292012215, tspeed)
Turn (l_arm, y_axis, -0.52359879016876, tspeed)
Turn (l_arm, z_axis, 0, tspeed)
Move (l_forearm, x_axis, 0, mspeed)
Move (l_forearm, y_axis, 0, mspeed)
Move (l_forearm, z_axis, 0, mspeed)
Turn (l_forearm, x_axis, -1.9198619127274, tspeed)
Turn (l_forearm, y_axis, 0, tspeed)
Turn (l_forearm, z_axis, 0, tspeed)
Move (right, x_axis, 0, mspeed)
Move (right, y_axis, 0, mspeed)
Move (right, z_axis, 0, mspeed)
Turn (right, x_axis, 0, tspeed)
Turn (right, y_axis, 0, tspeed)
Turn (right, z_axis, 0, tspeed)
Move (r_arm, x_axis, 0, mspeed)
Move (r_arm, y_axis, 0, mspeed)
Move (r_arm, z_axis, 0, mspeed)
Turn (r_arm, x_axis, -1.0471974611282, tspeed)
Turn (r_arm, y_axis, 0, tspeed)
Turn (r_arm, z_axis, -0.17453292012215, tspeed)
Move (r_forearm, x_axis, 0, mspeed)
Move (r_forearm, y_axis, 0, mspeed)
Move (r_forearm, z_axis, 0, mspeed)
Turn (r_forearm, x_axis, -2.0943949222565, tspeed)
Turn (r_forearm, y_axis, 0, tspeed)
Turn (r_forearm, z_axis, 0, tspeed)
Move (gun, x_axis, 0, mspeed)
Move (gun, y_axis, 0, mspeed)
Move (gun, z_axis, 0, mspeed)
Turn (gun, x_axis, 0, tspeed)
Turn (gun, y_axis, 0, tspeed)
Turn (gun, z_axis, 0, tspeed)
Move (fire, x_axis, 0, mspeed)
Move (fire, y_axis, 0, mspeed)
Move (fire, z_axis, 0, mspeed)
Turn (fire, x_axis, 0, tspeed)
Turn (fire, y_axis, 0, tspeed)
Turn (fire, z_axis, 0, tspeed)
Move (right_l, x_axis, 0, mspeed)
Move (right_l, y_axis, 0, mspeed)
Move (right_l, z_axis, 0, mspeed)
Turn (right_l, x_axis, 0, tspeed*2)
Turn (right_l, y_axis, 0, tspeed*2)
Turn (right_l, z_axis, 0, tspeed*2)
Move (shin_r, x_axis, 0, mspeed)
Move (shin_r, y_axis, 0, mspeed)
Move (shin_r, z_axis, 0, mspeed)
Turn (shin_r, x_axis, 0, tspeed)
Turn (shin_r, y_axis, 0, tspeed)
Turn (shin_r, z_axis, 0, tspeed)
Move (foot_r, x_axis, 0, mspeed)
Move (foot_r, y_axis, 0, mspeed)
Move (foot_r, z_axis, 0, mspeed)
Turn (foot_r, x_axis, 0, tspeed)
Turn (foot_r, y_axis, 0, tspeed)
Turn (foot_r, z_axis, 0, tspeed)
Move (left_l, x_axis, 0, mspeed)
Move (left_l, y_axis, 0, mspeed)
Move (left_l, z_axis, 0, mspeed)
Turn (left_l, x_axis, 0, tspeed*2)
Turn (left_l, y_axis, 0, tspeed*2)
Turn (left_l, z_axis, 0, tspeed*2)
Move (shin_l, x_axis, 0, mspeed)
Move (shin_l, y_axis, 0, mspeed)
Move (shin_l, z_axis, 0, mspeed)
Turn (shin_l, x_axis, 0, tspeed)
Turn (shin_l, y_axis, 0, tspeed)
Turn (shin_l, z_axis, 0, tspeed)
Move (foot_l, x_axis, 0, mspeed)
Move (foot_l, y_axis, 0, mspeed)
Move (foot_l, z_axis, 0, mspeed)
Turn (foot_l, x_axis, 0, tspeed)
Turn (foot_l, y_axis, 0, tspeed)
Turn (foot_l, z_axis, 0, tspeed)
end



function lookright (mspeed,tspeed)
Move (gp, x_axis, 0, mspeed)
Move (gp, y_axis, 0, mspeed)
Move (gp, z_axis, 0, mspeed)
Turn (gp, x_axis, 0, tspeed)
Turn (gp, y_axis, 0, tspeed)
Turn (gp, z_axis, 0, tspeed)
Move (cod, x_axis, 0, mspeed)
Move (cod, y_axis, -1, mspeed)
Move (cod, z_axis, 0, mspeed)
Turn (cod, x_axis, 0, tspeed)
Turn (cod, y_axis, 0, tspeed)
Turn (cod, z_axis, 0, tspeed)
Move (base, x_axis, 0, mspeed)
Move (base, y_axis, 0, mspeed)
Move (base, z_axis, 0, mspeed)
Turn (base, x_axis, 0, tspeed)
Turn (base, y_axis, -0.52359879016876, tspeed)
Turn (base, z_axis, 0, tspeed)
Move (head, x_axis, 0, mspeed)
Move (head, y_axis, 0, mspeed)
Move (head, z_axis, 0, mspeed)
Turn (head, x_axis, 0, tspeed)
Turn (head, y_axis, -0.34906584024429, tspeed)
Turn (head, z_axis, 0, tspeed)
Move (left, x_axis, 0, mspeed)
Move (left, y_axis, 0, mspeed)
Move (left, z_axis, 0, mspeed)
Turn (left, x_axis, 0, tspeed)
Turn (left, y_axis, 0, tspeed)
Turn (left, z_axis, 0.17453292012215, tspeed)
Move (l_arm, x_axis, 0, mspeed)
Move (l_arm, y_axis, 0, mspeed)
Move (l_arm, z_axis, 0, mspeed)
Turn (l_arm, x_axis, -0.17453292012215, tspeed)
Turn (l_arm, y_axis, 0, tspeed)
Turn (l_arm, z_axis, 0, tspeed)
Move (l_forearm, x_axis, 0, mspeed)
Move (l_forearm, y_axis, 0, mspeed)
Move (l_forearm, z_axis, 0, mspeed)
Turn (l_forearm, x_axis, -0.17453292012215, tspeed)
Turn (l_forearm, y_axis, 0, tspeed)
Turn (l_forearm, z_axis, 0, tspeed)
Move (right, x_axis, 0, mspeed)
Move (right, y_axis, 0, mspeed)
Move (right, z_axis, 0, mspeed)
Turn (right, x_axis, 0, tspeed)
Turn (right, y_axis, 0, tspeed)
Turn (right, z_axis, 0, tspeed)
Move (r_arm, x_axis, 0, mspeed)
Move (r_arm, y_axis, 0, mspeed)
Move (r_arm, z_axis, 0, mspeed)
Turn (r_arm, x_axis, -0.34906584024429, tspeed)
Turn (r_arm, y_axis, 0, tspeed)
Turn (r_arm, z_axis, 0, tspeed)
Move (r_forearm, x_axis, 0, mspeed)
Move (r_forearm, y_axis, 0, mspeed)
Move (r_forearm, z_axis, 0, mspeed)
Turn (r_forearm, x_axis, -0.34906584024429, tspeed)
Turn (r_forearm, y_axis, 0, tspeed)
Turn (r_forearm, z_axis, 0, tspeed)
Move (gun, x_axis, 0, mspeed)
Move (gun, y_axis, 0, mspeed)
Move (gun, z_axis, 0, mspeed)
Turn (gun, x_axis, 0, tspeed)
Turn (gun, y_axis, 0, tspeed)
Turn (gun, z_axis, 0, tspeed)
Move (fire, x_axis, 0, mspeed)
Move (fire, y_axis, 0, mspeed)
Move (fire, z_axis, 0, mspeed)
Turn (fire, x_axis, 0, tspeed)
Turn (fire, y_axis, 0, tspeed)
Turn (fire, z_axis, 0, tspeed)
Move (right_l, x_axis, 0, mspeed)
Move (right_l, y_axis, 0, mspeed)
Move (right_l, z_axis, 0, mspeed)
Turn (right_l, x_axis, 0, tspeed)
Turn (right_l, y_axis, 0, tspeed)
Turn (right_l, z_axis, -0.17453292012215, tspeed)
Move (shin_r, x_axis, 0, mspeed)
Move (shin_r, y_axis, 0, mspeed)
Move (shin_r, z_axis, 0, mspeed)
Turn (shin_r, x_axis, 0, tspeed)
Turn (shin_r, y_axis, 0, tspeed)
Turn (shin_r, z_axis, 0.17453292012215, tspeed)
Move (foot_r, x_axis, 0, mspeed)
Move (foot_r, y_axis, 0, mspeed)
Move (foot_r, z_axis, 0, mspeed)
Turn (foot_r, x_axis, 0, tspeed)
Turn (foot_r, y_axis, 0, tspeed)
Turn (foot_r, z_axis, 0, tspeed)
Move (left_l, x_axis, 0, mspeed)
Move (left_l, y_axis, 0, mspeed)
Move (left_l, z_axis, 0, mspeed)
Turn (left_l, x_axis, 0, tspeed)
Turn (left_l, y_axis, 0, tspeed)
Turn (left_l, z_axis, 0.17453292012215, tspeed)
Move (shin_l, x_axis, 0, mspeed)
Move (shin_l, y_axis, 0, mspeed)
Move (shin_l, z_axis, 0, mspeed)
Turn (shin_l, x_axis, 0, tspeed)
Turn (shin_l, y_axis, 0, tspeed)
Turn (shin_l, z_axis, -0.17453292012215, tspeed)
Move (foot_l, x_axis, 0, mspeed)
Move (foot_l, y_axis, 0, mspeed)
Move (foot_l, z_axis, 0, mspeed)
Turn (foot_l, x_axis, 0, tspeed)
Turn (foot_l, y_axis, 0, tspeed)
Turn (foot_l, z_axis, 0, tspeed)
end

function lookleft (mspeed,tspeed)
Move (gp, x_axis, 0, mspeed)
Move (gp, y_axis, 0, mspeed)
Move (gp, z_axis, 0, mspeed)
Turn (gp, x_axis, 0, tspeed)
Turn (gp, y_axis, 0, tspeed)
Turn (gp, z_axis, 0, tspeed)
Move (cod, x_axis, 0, mspeed)
Move (cod, y_axis, -1, mspeed)
Move (cod, z_axis, 0, mspeed)
Turn (cod, x_axis, 0, tspeed)
Turn (cod, y_axis, 0, tspeed)
Turn (cod, z_axis, 0, tspeed)
Move (base, x_axis, 0, mspeed)
Move (base, y_axis, 0, mspeed)
Move (base, z_axis, 0, mspeed)
Turn (base, x_axis, 0, tspeed)
Turn (base, y_axis, 0.52359873056412, tspeed)
Turn (base, z_axis, 0.17453292012215, tspeed)
Move (head, x_axis, 0, mspeed)
Move (head, y_axis, 0, mspeed)
Move (head, z_axis, 0, mspeed)
Turn (head, x_axis, 0, tspeed)
Turn (head, y_axis, 0.52359879016876, tspeed)
Turn (head, z_axis, 0, tspeed)
Move (left, x_axis, 0, mspeed)
Move (left, y_axis, 0, mspeed)
Move (left, z_axis, 0, mspeed)
Turn (left, x_axis, -0.34906584024429, tspeed)
Turn (left, y_axis, 0, tspeed)
Turn (left, z_axis, 0.17453292012215, tspeed)
Move (l_arm, x_axis, 0, mspeed)
Move (l_arm, y_axis, 0, mspeed)
Move (l_arm, z_axis, 0, mspeed)
Turn (l_arm, x_axis, -0.87266457080841, tspeed)
Turn (l_arm, y_axis, 0, tspeed)
Turn (l_arm, z_axis, 0, tspeed)
Move (l_forearm, x_axis, 0, mspeed)
Move (l_forearm, y_axis, 0, mspeed)
Move (l_forearm, z_axis, 0, mspeed)
Turn (l_forearm, x_axis, -0.34906587004662, tspeed)
Turn (l_forearm, y_axis, 0, tspeed)
Turn (l_forearm, z_axis, 0, tspeed)
Move (right, x_axis, 0, mspeed)
Move (right, y_axis, 0, mspeed)
Move (right, z_axis, 0, mspeed)
Turn (right, x_axis, 0, tspeed)
Turn (right, y_axis, 0, tspeed)
Turn (right, z_axis, 0, tspeed)
Move (r_arm, x_axis, 0, mspeed)
Move (r_arm, y_axis, 0, mspeed)
Move (r_arm, z_axis, 0, mspeed)
Turn (r_arm, x_axis, -0.52359879016876, tspeed)
Turn (r_arm, y_axis, 0.34906584024429, tspeed)
Turn (r_arm, z_axis, -0.34906584024429, tspeed)
Move (r_forearm, x_axis, 0, mspeed)
Move (r_forearm, y_axis, 0, mspeed)
Move (r_forearm, z_axis, 0, mspeed)
Turn (r_forearm, x_axis, -0.34906584024429, tspeed)
Turn (r_forearm, y_axis, 0, tspeed)
Turn (r_forearm, z_axis, 0.17453292012215, tspeed)
Move (gun, x_axis, 0, mspeed)
Move (gun, y_axis, 0, mspeed)
Move (gun, z_axis, 0, mspeed)
Turn (gun, x_axis, 0, tspeed)
Turn (gun, y_axis, 0, tspeed)
Turn (gun, z_axis, 0, tspeed)
Move (fire, x_axis, 0, mspeed)
Move (fire, y_axis, 0, mspeed)
Move (fire, z_axis, 0, mspeed)
Turn (fire, x_axis, 0, tspeed)
Turn (fire, y_axis, 0, tspeed)
Turn (fire, z_axis, 0, tspeed)
Move (right_l, x_axis, 0, mspeed)
Move (right_l, y_axis, 0, mspeed)
Move (right_l, z_axis, 0, mspeed)
Turn (right_l, x_axis, 0, tspeed)
Turn (right_l, y_axis, 0, tspeed)
Turn (right_l, z_axis, -0.17453292012215, tspeed)
Move (shin_r, x_axis, 0, mspeed)
Move (shin_r, y_axis, 0, mspeed)
Move (shin_r, z_axis, 0, mspeed)
Turn (shin_r, x_axis, 0, tspeed)
Turn (shin_r, y_axis, 0, tspeed)
Turn (shin_r, z_axis, 0.17453292012215, tspeed)
Move (foot_r, x_axis, 0, mspeed)
Move (foot_r, y_axis, 0, mspeed)
Move (foot_r, z_axis, 0, mspeed)
Turn (foot_r, x_axis, 0, tspeed)
Turn (foot_r, y_axis, 0, tspeed)
Turn (foot_r, z_axis, 0, tspeed)
Move (left_l, x_axis, 0, mspeed)
Move (left_l, y_axis, 0, mspeed)
Move (left_l, z_axis, 0, mspeed)
Turn (left_l, x_axis, 0, tspeed)
Turn (left_l, y_axis, 0, tspeed)
Turn (left_l, z_axis, 0.17453292012215, tspeed)
Move (shin_l, x_axis, 0, mspeed)
Move (shin_l, y_axis, 0, mspeed)
Move (shin_l, z_axis, 0, mspeed)
Turn (shin_l, x_axis, 0, tspeed)
Turn (shin_l, y_axis, 0, tspeed)
Turn (shin_l, z_axis, -0.17453292012215, tspeed)
Move (foot_l, x_axis, 0, mspeed)
Move (foot_l, y_axis, 0, mspeed)
Move (foot_l, z_axis, 0, mspeed)
Turn (foot_l, x_axis, 0, tspeed)
Turn (foot_l, y_axis, 0, tspeed)
Turn (foot_l, z_axis, 0, tspeed)
end

function bothhandgrip (mspeed,tspeed)
 Move (gp, x_axis, 0, mspeed)
 Move (gp, y_axis, 0, mspeed)
 Move (gp, z_axis, 0, mspeed)
 Turn (gp, x_axis, 0.34906584024429, tspeed)
 Turn (gp, y_axis, 0, tspeed)
 Turn (gp, z_axis, 0, tspeed)
 Move (cod, x_axis, 0, mspeed)
 Move (cod, y_axis, -6, mspeed)
 Move (cod, z_axis, 0, mspeed)
 Turn (cod, x_axis, 0, tspeed)
 Turn (cod, y_axis, 0, tspeed)
 Turn (cod, z_axis, 0, tspeed)
 Move (base, x_axis, 0, mspeed)
 Move (base, y_axis, 0, mspeed)
 Move (base, z_axis, 0, mspeed)
 Turn (base, x_axis, -0.34906584024429, tspeed)
 Turn (base, y_axis, 0, tspeed)
 Turn (base, z_axis, 0, tspeed)
 Move (head, x_axis, 0, mspeed)
 Move (head, y_axis, -1, mspeed)
 Move (head, z_axis, 1, mspeed)
 Turn (head, x_axis, 0, tspeed)
 Turn (head, y_axis, 0.52359879016876, tspeed) -- -
 Turn (head, z_axis, 0.34906584024429, tspeed)
 Move (left, x_axis, 0, mspeed)
 Move (left, y_axis, 0, mspeed)
 Move (left, z_axis, 0, mspeed)
 Turn (left, x_axis, -1.2217303514481, tspeed)
 Turn (left, y_axis, -0.52359879016876, tspeed)
 Turn (left, z_axis, -0.17453292012215, tspeed)
 Move (l_arm, x_axis, 0, mspeed)
 Move (l_arm, y_axis, 0, mspeed)
 Move (l_arm, z_axis, 0, mspeed)
 Turn (l_arm, x_axis, 0, tspeed)
 Turn (l_arm, y_axis, 0, tspeed)
 Turn (l_arm, z_axis, 0, tspeed)
 Move (l_forearm, x_axis, 0, mspeed)
 Move (l_forearm, y_axis, 0, mspeed)
 Move (l_forearm, z_axis, 0, mspeed)
 Turn (l_forearm, x_axis, -0.52359879016876, tspeed)
 Turn (l_forearm, y_axis, 0, tspeed)
 Turn (l_forearm, z_axis, 0, tspeed)
 Move (right, x_axis, 0, mspeed)
 Move (right, y_axis, 0, mspeed)
 Move (right, z_axis, 0, mspeed)
 Turn (right, x_axis, 0, tspeed)
 Turn (right, y_axis, 0, tspeed)
 Turn (right, z_axis, 0, tspeed)
 Move (r_arm, x_axis, 0, mspeed)
 Move (r_arm, y_axis, 0, mspeed)
 Move (r_arm, z_axis, 0, mspeed)
 Turn (r_arm, x_axis, -1.5707961320877, tspeed)
 Turn (r_arm, y_axis, 0.17453292012215, tspeed)
 Turn (r_arm, z_axis, 0, tspeed)
 Move (r_forearm, x_axis, 0, mspeed)
 Move (r_forearm, y_axis, 0, mspeed)
 Move (r_forearm, z_axis, 0, mspeed)
 Turn (r_forearm, x_axis, -0.17453292012215, tspeed)
 Turn (r_forearm, y_axis, 0, tspeed)
 Turn (r_forearm, z_axis, 0.17453292012215, tspeed)
 Move (gun, x_axis, 0, mspeed)
 Move (gun, y_axis, 0, mspeed)
 Move (gun, z_axis, 0, mspeed)
 Turn (gun, x_axis, 0, tspeed)
 Turn (gun, y_axis, 0, tspeed)
 Turn (gun, z_axis, 0, tspeed)
 Move (fire, x_axis, 0, mspeed)
 Move (fire, y_axis, 0, mspeed)
 Move (fire, z_axis, 0, mspeed)
 Turn (fire, x_axis, 0, tspeed)
 Turn (fire, y_axis, 0, tspeed)
 Turn (fire, z_axis, 0, tspeed)
 Move (right_l, x_axis, 0, mspeed)
 Move (right_l, y_axis, 0, mspeed)
 Move (right_l, z_axis, 0, mspeed)
 Turn (right_l, x_axis, -1.9198619127274, tspeed*2)
 Turn (right_l, y_axis, 0, tspeed)
 Turn (right_l, z_axis, 0, tspeed)
 Move (shin_r, x_axis, 0, mspeed)
 Move (shin_r, y_axis, 0, mspeed)
 Move (shin_r, z_axis, 0, mspeed)
 Turn (shin_r, x_axis, 1.7453291416168, tspeed*2)
 Turn (shin_r, y_axis, 0, tspeed)
 Turn (shin_r, z_axis, 0, tspeed)
 Move (foot_r, x_axis, 0, mspeed)
 Move (foot_r, y_axis, 0, mspeed)
 Move (foot_r, z_axis, 0, mspeed)
 Turn (foot_r, x_axis, 0, tspeed)
 Turn (foot_r, y_axis, 0, tspeed)
 Turn (foot_r, z_axis, 0, tspeed)
 Move (left_l, x_axis, 0, mspeed)
 Move (left_l, y_axis, 0, mspeed)
 Move (left_l, z_axis, 0, mspeed)
 Turn (left_l, x_axis, 0.34906584024429, tspeed)
 Turn (left_l, y_axis, 0, tspeed)
 Turn (left_l, z_axis, 0, tspeed)
 Move (shin_l, x_axis, 0, mspeed)
 Move (shin_l, y_axis, 0, mspeed)
 Move (shin_l, z_axis, 0, mspeed)
 Turn (shin_l, x_axis, 0.17453294992447, tspeed)
 Turn (shin_l, y_axis, 0, tspeed)
 Turn (shin_l, z_axis, 0, tspeed)
 Move (foot_l, x_axis, 0, mspeed)
 Move (foot_l, y_axis, 0, mspeed)
 Move (foot_l, z_axis, 0, mspeed)
 Turn (foot_l, x_axis, -0.69813168048859, tspeed)
 Turn (foot_l, y_axis, 0, tspeed)
 Turn (foot_l, z_axis, 0, tspeed)
end