	unitDef = {
	  unitname            = [[tpufo]],
	  name                = [[Flying Saucer]],
	  description         = [[Floating free on a continuum frequency]],
	  acceleration        = 0.8,
	  amphibious          = false,
	  bankscale           = [[0]],
	  maxBank			  = 0,
	  maxPitch 			  = 0,
	  bmcode              = [[1]],
	  brakeRate           = 5.75,
	  buildCostEnergy     = 0,
	  buildCostMetal      = 500,
	  builder             = false,
	  buildPic            = [[tpufo.png]],
	  buildTime           = 25,
	  canAttack           = true,
      canFly              = true,
	  canGuard            = true,
	  canMove             = true,
	  canPatrol           = true,
	  canstop             = [[1]],
	  category            = [[AIR]],
	  collide             = true,
	  corpse              = [[DEAD]],
      cruiseAlt           = 200,
      AirHoverFactor	  =0,
	  AirStrafe			  =0,
	  reclaimable         = false,
	collision = true,
	  defaultmissiontype  = [[VTOL_standby]],
	  explodeAs           = [[MEDIUM_UNIT]],
	  floater             = false,
          footprintx          = 3,
	  footprintZ          = 3,
      hoverAttack         = true,
	  airStrafe			  = false,
	  idleAutoHeal        = 0,
	  maneuverleashlength = [[1280]],
	  mass                = 125,
	  maxDamage           = 300,
	  maxVelocity         = 7,
	  minCloakDistance    = 75,
	  moverate1           = [[3]],
	  noAutoFire          = false,
	  noChaseCategory     = [[MINERALS SUB AIR]],
	  objectName          = [[ufo.s3o]],	  
	  seismicSignature    = 0,
	  selfDestructAs      = [[MEDIUM_UNIT]],
		Upright = true,
	  sfxtypes            = {
	
	    explosiongenerators = {
		"custom:tpbeamcone",
		"custom:orc_machinegun_muzzle",
	    },
	
	  },

	    --HITBOX--
	  collisionVolumeTest       =  1,
	  collisionVolumeOffsets    =  [[0 0 0]],
	  collisionVolumeType       =  [[sphere]],
	  collisionVolumeScales     = [[65 65 65]],  -- [[20 30 20]],

	  side                = [[NKG]],
	  sightDistance       = 600,
	  smoothAnim          = true,
	  steeringmode        = [[1]],
	  TEDClass            = [[VTOL]],
	  turnRate            = 800, --693
	  turnRadius		  = 1, --5
	  workerTime          = 0,
      script              = [[tpufo.lua]],
	
	  weapons             = {		
	    {
	      def                = [[Beam]],
	      cylinderTargeting      	  = 1,
		  WeaponMainDir1=[[0 -1 0]],  --x:0 y:0 z:1 => that's forward!
		  MaxAngleDif1=90,       --45  --90° from side to side, or 45° from center to each direction
	      onlyTargetCategory = [[VEHICLE LAND BUILDING BIO SEA]],
	    },
		{
			def= "SHIELD",
		},
	
	  },
	
	
	  weaponDefs          = {
		Bombs = {
	      name                    = [[Bombs]],
	      areaOfEffect            = 256,
	      avoidFeature            = false,
	      avoidFriendly           = false,
	      burst                   = 3,
	      burstrate               = 0.2,
	      commandfire             = true,
	      craterMult              = 0.25,
	      collideFriendly         = true,
		  cylinderTargeting	  = 1,
	      damage                  = {
			Normal = 300,
	      },	
	      dropped                 = true,
	      edgeEffectiveness       = 0.7,
	      explosionGenerator      = [[custom:PLASMA_Expl]],
	      tolerance               = 64000,
	      manualBombSettings      = true,
	      model                   = [[bantimechmissile.s3o]],
	      myGravity               = 0.7,
	      range                   = 500,
		  cylinderTargeting	  = 1,
	      reloadtime              = 2,
	      --soundHit                = [[ct/shot3]],
	      sprayangle              = 64000,
	      startvelocity           = 2,
	      weaponType              = [[AircraftBomb]],
	    },
	
	    Rockets = {
	      name                    = [[Rockets]],
	      areaOfEffect            = 256,
	      avoidFeature            = false,
	      avoidFriendly           = false,
	      burst                   = 2,
	      Projectiles			  = 2,
		  burstrate               = 0.2,
	      --commandfire             = true,
	      craterMult              = 0.4,
	      collideFriendly         = true,
	
	      damage                  = {
		Normal = 40,
	      },
			CegTag				 = "tpmisslesmoke",
			model                   = [[projmissle.s3o]],
	      Accuracy				  =	2000,
		  dance                   = 30,
	      FixedLauncher			  = true,
		  wobble                  = 1000,
	      explosionGenerator      = [[custom:tpmissleimpact]],
	      flightTime              = 2.5,	      
	      lineOfSight             = true,
	      range                   = 500,
		  cylinderTargeting	  = 1,
	      reloadtime              = 2.5, --1.5
	      --smokeTrail              = true,
	      soundHit                = [[kanoba/SabotHitRemake.ogg]],
	      soundStart              = [[kanoba/RockLit1Remake.ogg]],
	      BurnBlow				  = 0,		  
		  tolerance               = 16000,
	      tracks                  = true,
	      Turnrate				  = 16000,
		  turret                  = false,
	      weaponType              = [[MissileLauncher]],
	      weaponVelocity          = 1500,
	      startVelocity           = 100,
	      weaponAcceleration      = 150,
	    },	
		
		Beam ={
		  interceptedByShieldType = 1,
		  MinIntensity = 1,	--damage always same no matter distance
		  Intensity       = 1, --1
		  cylinderTargeting	  = 1,		  
		  avoidFriendly      = 0,              
	      collideFriendly    = false,
		  --FixedLauncher			  = true,
		  areaOfEffect       = 64,
		  beamlaser          = 1,
		  LargeBeamLaser	 = 1,
		  beamTime           = 0.5, --0.5
		  thickness			 = 50,
		  beamWeapon         = true,
		  HardStop			=0,
		  LaserFlareSize	= 0,
		 beamdecay=0.5,
		 beamttl=6,--20
		  SweepFire=1,
		  RGBColor=[[0 1 0]],
		  RGBCOLOR2=[[0 0.8 0]],
		  craterMult         = 0,
		  duration           = 3,
		  --explosionGenerator = "custom:tpsmokecloud",
		  filename           = "weapons/beamweapons.tdf",
		  fireStarter        = 290,
		  --id                 = 138,
		  impulseFactor      = -5,		  -- -100 kicks everything across the map=funny		  
		  name               = "Beam",
		  noSelfDamage       = true,
		  range              = 300,
		  reloadtime         = 0.75, --0.5
		  renderType         = 0,
		  --soundHit           = "laserhit1",
		  --soundStart         = "longbeamfire",
		  tolerance          = 90000,
		  turret             = false,
		  weaponVelocity     = 1300,
		  damage = {
			normal			= 30, --160
		  },

		},
		
	SHIELD      = {	--thanks zk
		  name                    = [[Energy Shield]],
		  craterMult              = 0,

		  damage                  = {
			default = 100,
			Normal = 100,
		  },
		  FixedLauncher			  = true,
		  exteriorShield          = true,
		  impulseFactor           = 0,
		  --interceptedByShieldType = 1,
		  isShield                = true,
		  shieldAlpha             = 0.3,
		  shieldBadColor          = [[0.5 0 0]],
		  shieldGoodColor         = [[0.8 1 0.9]],
		  shieldInterceptType     = 1,
		  shieldPower             = 400,
		  shieldPowerRegen        = 15,
		  shieldPowerRegenEnergy  = 0,
		  shieldRadius            = 75,
		  shieldRepulser          = false,
		  shieldStartingPower     = 200,
		  smartShield             = true,
		  texture1                = [[ufoshield]],
		  visibleShield           = true,
		  visibleShieldHitFrames  = 10,
		  visibleShieldRepulse    = true,
		  weaponType              = [[Shield]],
		},
	
	  },	
	}
	
	return lowerkeys({ tpufo = unitDef })